### ISSUE TITLE
Farming skill is doubled up without any reason + unenabled skills still working

### ISSUE THREAD

**Issue by trushniuser** [Archy-X/AuraSkills#112]
### Server software and version

Spigot 1.16.5

### Expected behavior

Normal XP sources from farming skill and unenabled skills, which were set to off in the config.

### Actual behavior

All XP sources from farming skill are doubled up without any reason (I do not have any multipliers or modifications on this skill). 
Also, unenabled skills, which were set off in the config, are still working.
https://youtu.be/leHWoa0w79c
https://youtu.be/Kv31M8bVWak

### How to reproduce

Fix the issue with doubled xp
Fix the issue with skills

### Additional information

This bug was also reported on the discord server from user _Luke_#0001 and me (Lesoules#7877)

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by Archy-X** [comment]
Can you send a plugin list? There might be a plugin that is calling BlockBreakEvent twice

**Comment by trushniuser** [comment]
Plugins (12): LuckPerms, Vault, PlaceholderAPI, GoldBank, ProtocolLib, Towny, TownyChat, Skript, HolographicDisplays, DeluxeMenus, skript-placeholders, AureliumSkills
