### ISSUE TITLE
Overlapping Classes Compile Warnings

### ISSUE THREAD

**Issue by Archy-X** [Archy-X/AuraSkills#134]
### Server software and version

N/A

### Expected behavior

N/A

### Actual behavior

Compiling as of Beta 1.3.9 produces the following warning:
```
[WARNING] Slate-4ed646a318.jar, SmartInvs-1.3.0.jar define 26 overlapping classes: 
[WARNING]   - fr.minuskube.inv.util.Pattern
[WARNING]   - fr.minuskube.inv.InventoryManager
[WARNING]   - fr.minuskube.inv.InventoryManager$PlayerInvTask
[WARNING]   - fr.minuskube.inv.content.Pagination
[WARNING]   - fr.minuskube.inv.content.SlotIterator
[WARNING]   - fr.minuskube.inv.content.InventoryContents$Impl
[WARNING]   - fr.minuskube.inv.content.Pagination$Impl
[WARNING]   - fr.minuskube.inv.ClickableItem
[WARNING]   - fr.minuskube.inv.opener.ChestInventoryOpener
[WARNING]   - fr.minuskube.inv.opener.InventoryOpener$1
[WARNING]   - 16 more...
```

This is most likely an issue with the build.gradle of Slate (https://github.com/Archy-X/Slate) but I can't seem to find why it's duplicating SmartInvs.

### How to reproduce

Compile the plugin using maven clean install

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by Archy-X** [comment]
@zhro I feel like I could use your help here. If you know the issue then you can open a PR on the Slate repo.

**Comment by zhro** [comment]
Although very late, I just got this notification when checking my GitHub. Thank you for tagging me. Is this still something that needs to be looked at?

**Comment by Archy-X** [comment]
Yes, the build.gradle of Slate
