### ISSUE TITLE
sk resethealth not resetting health

### ISSUE THREAD

**Issue by billynational** [Archy-X/AuraSkills#151]
### Server software and version

Paper 1.19.2

### Expected behavior

All players health / mana reset

### Actual behavior

SOme players dont reset

### How to reproduce

Not sure

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by Archy-X** [comment]
Have you made sure every player is offline when you run the command?
