### ISSUE TITLE
Speed, Crit Chance and Crit Damage as actual stats and also option for stat formulas

### ISSUE THREAD

**Issue by PrimalPower** [Archy-X/AuraSkills#183]
### Feature description

Basically speed, crit chance and crit damage made into proper stats similar to strength, toughness, regeneration etc. (Speed increases movement speed by certain % and crit chance is the chance to deal crit damage). The archery and fighting skill abilities (Crit Chance and Crit Damage) will provide the certain amount of these stats. Base crit chance and crit damage can be defined in config.

I am using custom item plugins so this change will allow me to use them for my custom items due to the plugin integrations and I will be able to use these stat values as placeholders.

I would also like there to be an option to change the formula used for the stats similar how the Skill XP formula can be changed. There could be an option for each stat like use_custom_formula (defaults to false). I mainly want to change this for the toughness stat due to it currently being an exponential instead of linear formula and I want the consistency

Colouring Suggestions:
Strength - Dark Red - &4 (Same as before)
Health - Red - &c (Same as before)
Regeneration - Orange - &6 (Same as before)
Toughness - Lime Green - &a (was Purple - &5 before)
Luck - Dark Green - &2 (Same as before)
Wisdom - Light Blue - &b (was dark blue - &9/&1 before idk)
Crit Damage - Dark Blue - &1
Crit Chance - Purple - &5
Speed - White - &f

**Comment by Archy-X** [comment]
This has been added in 2.0+, as well as a configurable formula for Toughness in stats.yml.
