### ISSUE TITLE
Custom xp sources are not shown in xp sources menus

### ISSUE THREAD

**Issue by Pexep** [Archy-X/AuraSkills#185]
### Server software and version

Beta 1.3.19

### Expected behavior

When custom xp sources are added in file sources_config.yml, the custom xp sources must be visible in the xp sources menus.

### Actual behavior

After adding custom xp sources, xp gains for these sources works but these xp sources don't appear in the xp sources menu.

### How to reproduce

1. add custom xp sources on file sources_config.yml
2. reload AureliumSkills
3. open the skill's xp sources menu

### Additional information

![image](https://github.com/Archy-X/AureliumSkills/assets/104359902/44738eab-4612-408b-90c0-c4ef8a9bcf9e)
![image](https://github.com/Archy-X/AureliumSkills/assets/104359902/5c602e43-0dba-4abb-bb00-5484471330a9)

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by Archy-X** [comment]
Fixed in 2.0 since the sources system overhaul.
