### ISSUE TITLE
Some abilitiy text varibles are missing

### ISSUE THREAD

**Issue by Pexep** [Archy-X/AuraSkills#188]
### Server software and version

Beta 1.3.19

### Expected behavior

Write {value_2} in some ability text should print the second value of the ability, if it has a second value.

### Actual behavior

Write {value_2} in some ability text (descriptions and infos) doesn't print the second value for these abilities : 

- lightning_blade : doesn't print duration
- speed_mine : doesn't print the value of haste effect
- bleed : doesn't print number of ticks

Value of these abilities can scale with the ability level, it's the reason why I've created this github issue, we can't just write a value in file.

### How to reproduce

Write "{value_2}" in an ability description that i've writted above.

### Additional information

Some other abilities support the "{value_2}" variable.

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by Archy-X** [comment]
For lightning blade, use the {duration} placeholder to display duration. For speed mine, use the {haste_level} placeholder. As for bleed, you will have to change the value in the message manually to reflect the configured value since the number of ticks is an option, not the value_2 (value_2 is already taken up by the amount of damage).

**Comment by Pexep** [comment]
Ok thanks !
Is it possible to add a placeholder for the number of bleed ticks please ? Because it's not necessarily a static value.
Thanks :)

**Comment by Archy-X** [comment]
Fixed in 2.0.
