### ISSUE TITLE
Abilities order in abilities menu

### ISSUE THREAD

**Issue by Pexep** [Archy-X/AuraSkills#195]
### Feature description

I would like abilities to be displayed in a logical order in the ability menus. Currently they keep the default order and it is impossible to change this order. I find it unfortunate because if we choose to change the order in which they are unlocked, this order will not change, for example. I would like to we can choose the order in which they are displayed or that they are displayed in the order in which they are unlocked.

**Comment by Garrett1199** [comment]
I was also searching everywhere to see if this is possible. I would love to see this feature added.

**Comment by Archy-X** [comment]
This is already possible (albiet not documented) by adding and editing slots in menus/abilities.yml like this:
```
templates:
  locked_ability:
    options:
      slots: ['1,1', '1,2', '1,3', '1,4', '1,5']
```
This should also be added to unlocked_ability.
