### ISSUE TITLE
various cross server data syncronization problems

### ISSUE THREAD

**Issue by aaa8881** [Archy-X/AuraSkills#203]
### Server software and version

1.19.3 paper

### Expected behavior

mana and abilities should be syncronzied properly across servers

### Actual behavior

First, you need multiple servers that aureliumSkills are installed and set up with mysql.

1. Mana is not properly synced. it does update MANA column in db , but it overwrites to value of individual server. I think it's because cache in specific server comes in first than database.
2. active skill cooldown is counting separately per server
3. activate any sort of active skill -> use for a while -> swap server to a server where skill is also installed -> come back to original server , skill cooldown is reset. 

### How to reproduce

same as above

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by Archy-X** [comment]
These issues should be fixed in 2.0, since mana ability cooldowns are now stored in the db. Reopen this issue if you still encounter issues.
