### ISSUE TITLE
Locked skills increase stats

### ISSUE THREAD

**Issue by Pexep** [Archy-X/AuraSkills#208]
### Server software and version

Beta 1.3.21

### Expected behavior

When skills are locked they can't increase stats level.

### Actual behavior

If a skill is locked, all of stats points that the level of this skill give to the player are given.

### How to reproduce

1. Set all skills at level 1
2. Set one skill at level 100
3. Set the permission of this skill false (aureliumskills.{skill})
4. Look the attributs level

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by Archy-X** [comment]
Fixed in 446af9ecaee70f71b82a10f9d2331cb53fdd489f
