### ISSUE TITLE
Custom loots xp is not given (excavation & fishing)

### ISSUE THREAD

**Issue by Pexep** [Archy-X/AuraSkills#212]
### Server software and version

Beta 1.3.21

### Expected behavior

Custom loots (from excavation and fishing) should give rare or epic xp amount (set in sources_config.yml) or the custom loot xp amount if the key "xp" is defined for this item. 

### Actual behavior

The custom loot xp amount, for items which the "xp" key is defined, is never given. It's as if the key "xp" doesn't exist at all.
So for all custom loots, if the basic item of the loot is defined as a source (example : cod for fishing, but rename ...), it's the basic item amount of xp that is given (the amount of xp for a basic cod defined in sources_config.yml). And if the loot is not defined as a source (example : stone for fishing) it's the correct rare or epic amount of xp, defined in sources_config.yml, that is given.

So : 
- key "xp" in loots files dosen't work
- for loots which the item is defined for the skill in sources_config.yml, the rare or epic amount of xp is not applied

### How to reproduce

1. In loots files, define one loot with the key "xp" and another without the key "xp" but set the "item" key as an item which is defined in sources_config.yml
2. See that for the first one, you don't get the xp of the "xp" key and that for the other, you don't get the xp for a rare or epic loot.

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by Pexep** [comment]
Hello, i've found the problem. It's because in the fishing/excavation loot files we don't add .0 to the xp amount of th xp key.
It provides a parsing error : 
java.lang.ClassCastException: Cannot cast java.lang.Integer to java.lang.Double
at java.lang.Class.cast(Class.java:3889) ~[?:?]
at com.archyx.lootmanager.util.OptionsProvider.getOption(OptionsProvider.java:29) ~[AureliumSkills-Beta1.3.22.jar:?]
at com.archyx.aureliumskills.loot.handler.LootHandler.giveXp(LootHandler.java:145) ~[AureliumSkills-Beta1.3.22.jar:?]

Perhaps it should try to convert the xp key if it's not a double ?

**Comment by Pexep** [comment]
New edit : In case of a custom item that is in basic sources (example : cod for fishing) the custom xp amount is correctly given but the basic xp is given too (example : the xp af the basic cod + the xp of the custom cod).

**Comment by Archy-X** [comment]
Should be fixed in 2.0, reopen if it isn't.
