### ISSUE TITLE
When Bleed kill ennemy, player does not receive xp

### ISSUE THREAD

**Issue by Pexep** [Archy-X/AuraSkills#215]
### Server software and version

Beta 1.3.21

### Expected behavior

When Bleed kill ennemies, player who applied bleed should receive xp for killing the enemy.

### Actual behavior

When Bleed kill ennemies, player who applied bleed don't receive xp for killing the enemy.

### How to reproduce

1. Set Bleed with high damages and probability to be applied
2. Take a mob with little HP
3. hit it and see that you don't receive xp after his death

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by Archy-X** [comment]
Fixed in 689e3b377562a71a5c5c6c938a49881494f0c670
