### ISSUE TITLE
Share ability cooldown data in MySQL

### ISSUE THREAD

**Issue by flowGH1** [Archy-X/AuraSkills#219]
### Feature description

The player data and mana information are uploaded to MySQL, but the ability cooldowns are not. Even though MySQL is integrated and used with the BungeeCord server, the ability cooldowns operate individually for each server.

Is it possible to upload the ability cooldowns to MySQL so that all backend servers have the same cooldowns?

**Comment by Archy-X** [comment]
This should be fixed in 2.0 versions.
