### ISSUE TITLE
status bar mana is displayed as rounded instead of floor

### ISSUE THREAD

**Issue by asheden** [Archy-X/AuraSkills#222]
### Server software and version

paper 1.20.1

### Expected behavior

the mana should be displayed rounded down, so it never tells the player they have more mana than they actually have.

### Actual behavior

the mana is displayed rounded to the closest integer, so it often makes the player think they can activate a skill that they can't (especially when mana regeneration is set as a small number)

### How to reproduce

activate status bar and enable mana
make player mana lower than max mana
make mana regeneration a small number for a clearer view of the bug
attempt to use a skill as soon as the game tells you you have enough mana
develop trust issues

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by Archy-X** [comment]
Action bar mana uses floor as of 2.0.
