### ISSUE TITLE
Reward Partial XP for Damage Config

### ISSUE THREAD

**Issue by Dannydads** [Archy-X/AuraSkills#228]
### Feature description

I'm not entirely sure this would be even possible, but it would nice if instead of rewarding experience solely to the killer of the mob, either reward it as damage is being done (damage * mob value / mob max health), or track damage percentages of boss monsters to divvy up rewards. 

At least with me, in the early game wither and enderdragon fights tend to be done in a group and it can be rough to have all the exp go just to whomever got the last blow, instead of rewarding everybody's effort. 

It could be done just as a configuration option, since it could be a bit more resource intensive.

**Comment by Archy-X** [comment]
You can do this in 2.0+ by change the default.trigger option in sources/fighting.yml and archery.yml to damage. This gives XP as a fraction of max health whenever a player damages a mob.
