### ISSUE TITLE
Max heart reset to default heart when a player died

### ISSUE THREAD

**Issue by rcastano02** [Archy-X/AuraSkills#230]
### Server software and version

1.3.23

### Expected behavior

I have all the default settings of the plugins enabled, but when a player dies, their health is reset by default. For example, a player has 12 hearts, and when they die, they return to the default 10 hearts that vanilla has.

Mohist-1.20.1
Version minecraft: 1.20.1
Version plugins: 1.3.23

![image](https://github.com/Archy-X/AureliumSkills/assets/143288925/fa2f63fd-2606-46ec-a9ab-3fbed2694933)

### Actual behavior

a player has 12 hearts, and when they die, they return to the default 10 hearts that vanilla has.

### How to reproduce

when a player dies desaparecen los corazones

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by Archy-X** [comment]
Mohist and any modded hybrid servers are not supported, these issues are usually caused by the server.
