### ISSUE TITLE
increased xp for killing disguised mobs in mythic mobs

### ISSUE THREAD

**Issue by rysato1** [Archy-X/AuraSkills#231]
### Server software and version

Paper 1.20.2

### Expected behavior

xp for killing mythic mobs should be higher than from a normal mob (it's a disguised zombie, for example..)

### Actual behavior

he doesn't get increased xp, he only gets it for killing zombies

### How to reproduce

all we did was update minecraft server version to version 1.20.2 from version 1.19.

### Additional information

we have no idea what to do with it.

command is via CMI which adds increased experience for killing mythic mobs moba

(mythic mobs has a free version and CMI I guess too.)

Does anyone know how to fix it? or should I write on mythic mobs or CMI report?

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by Fly1337** [comment]
If this feature once worked with MythicMobs, it might have been added on their end. WorldGuard, PlaceholderAPI, HolographicDisplays, DecentHolograms, Vault, ProtocolLib, Luckperms, Slimefun and Towny are the only Plugins it integrates with.
