### ISSUE TITLE
Mana Bug

### ISSUE THREAD

**Issue by SrMonsterYT** [Archy-X/AuraSkills#233]
### Server software and version

Pufferfish git-Pufferfish-27 (MC: 1.20.1)

### Expected behavior

consume mana

### Actual behavior

it's not consuming mana, see the video where the player activates the skill and the mana is not reduced, but -5 mana appears.

### How to reproduce

video: https://www.youtube.com/watch?v=Q3ODu8dwEo4

### Additional information

version plugin: AureliumSkills-Beta1.3.23

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by Archy-X** [comment]
This is most likely because the player regenerated the mana already between the time the ability was activated and the action bar was shown again. You can nerf the mana regen rate by decreasing the regeneration.mana-modifier in config.yml.
