### ISSUE TITLE
Add a command to refresh an ability

### ISSUE THREAD

**Issue by Nanpure** [Archy-X/AuraSkills#249]
### Feature description

I am trying to debug a crash which triggers with an ability, but I must wait minutes for it to refresh. Please add a command to fresh abilities for OP players for testing purposes.

**Comment by Archy-X** [comment]
This isn't about your feature request directly but is your crash possibly related to the Terraform mana ability? It can cause crashes with other plugins like Enchant plugins that allow breaking multiple blocks at the same time, so one or the other feature has to be disabled. You can disable terraform in mana_abilities.yml.

**Comment by Archy-X** [comment]
This has been added
