### ISSUE TITLE
Alchemist ability with custom effect potions

### ISSUE THREAD

**Issue by Wupin** [Archy-X/AuraSkills#251]
### Server software and version

git-Paper-448 (MC: 1.20.4)

### Expected behavior

When brewing a potion with a custom potion effect (set by potionMeta#addCustomEffect), AuraSkill will completely replace the entire lore of the item, so it will wipe previous lore. And after drinking the potion, the effect will not extend by the promised value.
Example item NBT Tags: https://pastebin.com/rn7ZFXbT

### Actual behavior

The item's lore should not be completely replaced, but the additional time line should only have be inserted. Potion should add another 2:22 effect duration , but it doesn't.

### How to reproduce

Register a [PotionMix ](https://jd.papermc.io/paper/1.20/io/papermc/paper/potion/PotionMix.html) recipe with custom potion effects and then brew a potion

### Additional information

https://youtu.be/V1vSJbOSnBs

### Agreements

- [X] I am running the latest version of AuraSkills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/auraskills/incompatibilities)
- [X] My version of Minecraft is supported by AuraSkills

**Comment by Archy-X** [comment]
Can you see if the issue is fixed in the latest [dev build](https://aurelium.dev/auraskills/download?channel=dev)?

**Comment by Wupin** [comment]
Yep, fixed.
