### ISSUE TITLE
issue French translation

### ISSUE THREAD

**Issue by Draghonir** [Archy-X/AuraSkills#270]
### Server software and version

1.20.4

### Expected behavior

Hello, I just found an error in the French translation. When we go to the stats menu, the number 7 appears next to each skill, as shown in the attached photo, but there is no bug

### Actual behavior

no error

### How to reproduce

set french traslate

### Additional information

![AZ](https://github.com/Archy-X/AuraSkills/assets/107469643/66a3c9ae-3395-4cb7-9af5-b0d5d2751a04)

### Agreements

- [X] I am running the latest version of AuraSkills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/auraskills/incompatibilities)
- [X] My version of Minecraft is supported by AuraSkills

**Comment by Archy-X** [comment]
You can fix this yourself by removing the 7 in messages/messages_fr.yml under menus.stats.skills (line 590). This has been fixed in the latest version for newly generated files.

**Comment by Draghonir** [comment]
fixed thank you
