### ISSUE TITLE
"Alchemist" Duration Increase allows multiple durations to be stored on one potion

### ISSUE THREAD

**Issue by RelinquishMental** [Archy-X/AuraSkills#278]
### Server software and version

Paper 1.20.6

### Expected behavior

When I begin a new brew cycle, I expect any completed potions that have been left in the stand to remain unaltered by the new brewing. 

I expect the same behavior as vanilla.

### Actual behavior

When I begin a new brew cycle, somehow any completed potions that have been left in the stand receive another increased Alchemist duration applied to their tooltip. 

Eventually this makes the game think that there are multiple potions in the stand, and when I interact with the potions or the stand, I get kicked by NBT tag too large errors

### How to reproduce

Give yourself Alchemy 1000. (I had alchemy mid 400s, but any high value should reproduce)

Brew potions with a duration, but only remove 1 potion from the brew stand, leaving 2 completed potions. 

Repeat this to get multiple durations on one pot, to confirm the bug. 

If you repeat until you get many durations (more than can be viewed on screen), you will eventually run into the "NBT tag too large issue", as well. 

### Additional information

Is this something you have seen before?

### Agreements

- [X] I am running the latest version of AuraSkills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/auraskills/incompatibilities)
- [X] My version of Minecraft is supported by AuraSkills

**Comment by Archy-X** [comment]
This has been fixed in 2.1.0.

**Comment by RelinquishMental** [comment]
Awesome thanks
