### ISSUE TITLE
Item flag "hide_attributes" not working on menus

### ISSUE THREAD

**Issue by VinceSMC** [Archy-X/AuraSkills#280]
### Server software and version

Paper 1.20.6 (paper-1.20.6-86)

### Expected behavior

Hide item attributes.

### Actual behavior

Item attributes are no longer hidden (it's related to MC 1.20.5+).

### How to reproduce

Add:
```
flags:
  - hide_attributes
```

### Agreements

- [X] I am running the latest version of AuraSkills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/auraskills/incompatibilities)
- [X] My version of Minecraft is supported by AuraSkills

**Comment by Archy-X** [comment]
I've tried to find a solution to this issue when coding 1.20.6 support but I think it's a limitation with the Bukkit API or the new item components system. There doesn't seem to be a way to hide default modifiers in an empty attribute_modifiers component by itself without the tag being removed.

**Comment by VinceSMC** [comment]
Hi Archy,

Thanks for the reply. You might want to explore using:
`itemMeta.setAttributeModifiers(Material.IRON_SWORD.getDefaultAttributeModifiers(EquipmentSlot.HAND));`

Appreciate your work!

**Comment by Archy-X** [comment]
Thanks for the snippet, it should be fixed in 2.1.0.
