### ISSUE TITLE
Unstable spigot 1.21 | Task #25 for AuraSkills v2.1.2 generated an exception

### ISSUE THREAD

**Issue by snow-cart** [Archy-X/AuraSkills#293]
### Server software and version

Spigot 1.21 (unstable)

### Expected behavior

No error logs

### Actual behavior

![image](https://github.com/Archy-X/AuraSkills/assets/160158910/52b571b5-424b-4454-9c51-c288c1d683db)

### How to reproduce

Build spigot for 1.21 from source.

### Additional information

This isn't urgent as it might be spigot related, using unstable spigot 1.21 release, with AuraSkills 2.1.2 stable release. 

No, my version of minecraft is not supported, but reporting this ahead of time, so you could possibly just take a look at it.

### Agreements

- [X] I am running the latest version of AuraSkills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/auraskills/incompatibilities)
- [ ] My version of Minecraft is supported by AuraSkills

**Comment by Archy-X** [comment]
2.1.2 did not support 1.21, but 2.1.3 does and fixes these errors.
