### ISSUE TITLE
RegionManager#loadRegion(Region) does disk I/O on server thread

### ISSUE THREAD

**Issue by AnttiMK** [Archy-X/AuraSkills#306]
### Server software and version

Paper version 1.21-89-master@44c3dd0 (2024-07-17T19:55:30Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

### Expected behavior

Plugin to function so that blocking operations (such as disk I/O) are run off the main thread

### Actual behavior

![image](https://github.com/user-attachments/assets/2331d0cb-8bc3-4332-921a-3fcada4d2f89)

### How to reproduce

1. Extend a piston so that RegionManager#loadRegion(Region) is called (?, not sure of the conditions here)

### Additional information

AuraSkills v2.1.5

### Agreements

- [X] I am running the latest version of AuraSkills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/auraskills/incompatibilities)
- [X] My version of Minecraft is supported by AuraSkills

**Comment by Archy-X** [comment]
This should be fixed as of 2.2.3.
