### ISSUE TITLE
Issues with advanced enchantments

### ISSUE THREAD

**Issue by Vehzx** [Archy-X/AuraSkills#318]
### Server software and version

1.21.1 Paper-77

### Expected behavior

Multiple skills are bugged due to AuraSkills, however I will showcase just one here.

The "Overload" enchantment from AdvancedEnchantments adds hearts to the player using the potion effect.

There are many other skills that straight up do not work.

See Video1 for the expected behaviour for the enchant.

https://github.com/user-attachments/assets/a2575610-1fdb-461f-810d-8ee64b38deb5

### Actual behavior

Auraskills instead reverts this, making the player lose hearts instead of gaining them (see Video2).

https://github.com/user-attachments/assets/9a17fb38-c80d-4a27-b085-657c89b89b7f

### How to reproduce

Install the latest AdvancedEnchantments and the latest AuraSkills on the server (im using paper-77 1.21.1)
Get yourself any piece of armor (I use an iron chestplate, but it doesnt matter).
Hold in hand and then "/ae enchant overload 1" (again you can use any tier of the enchant, doesnt matter)
equip chestplate and see it removes the health instead of giving extra hearts.

### Additional information

I see a post from 2023 about compatibility issues, I was going to add to that post, however it's over a year old.

AdvancedEnchantments can be found here: https://www.spigotmc.org/resources/1-17-1-21-1-⭕-advancedenchantments-⭐-450-custom-enchants-⭐create-custom-enchantments-✅.43058/

AdvancedEnchantments API: https://ae.advancedplugins.net/for-developers/plugin-api

### Agreements

- [X] I am running the latest version of AuraSkills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/auraskills/incompatibilities)
- [X] My version of Minecraft is supported by AuraSkills

**Comment by Archy-X** [comment]
This could just be the health scaling feature working as intended, which gives extra visual hearts at higher HP thresholds to work better with high HP values (this is only visual, actual HP is still the same). Set traits.auraskills/hp.health_scaling to false in stats.yml to see if that results in the behavior you want.

**Comment by Vehzx** [comment]
Setting 'health_scaling: false' under auraskills/hp shows my default hearts at 6? then adding my armor does indeed add 3 hearts as intended, however without auraskills, players have 10 hearts and equipping the chestpiece gives 13 hearts (this is what im trying to achieve). Can I achieve that while still having auraskills installed?

**Comment by Vehzx** [comment]
Nevermind I have fixed it, "force_base_health: true" "health_scaling: false" with has solved my problem, you can close this post, thank you.
