### ISSUE TITLE
Error with BossBar Progress in AuraSkills v2.2.3 (EntityDamageByEntityEvent)

### ISSUE THREAD

**Issue by thisisaef** [Archy-X/AuraSkills#322]
### Server software and version

PaperMC version 1.21.1-110-master@6d7a438

### Expected behavior

**Describe the Bug**: The plugin AuraSkills v2.2.3 throws an error during the EntityDamageByEntityEvent event, specifically related to setting the BossBar progress. The error occurs due to a java.lang.IllegalArgumentException stating that the progress must be between 0.0 and 1.0 but receives NaN.

**Expected Behavior**: The plugin should correctly calculate and set the progress for the BossBar without throwing an exception.

### Actual behavior

The plugin throws an exception when attempting to set the BossBar progress due to an invalid value (NaN).

### How to reproduce

1. Trigger an entity damage event (e.g., player or mob combat).
2. The AuraSkills plugin tries to handle the event, leading to the BossBar progress issue.

### Additional information

Log Error: https://paste.helpch.at/nofebuhocu.php
Latestlog: https://paste.helpch.at/ukemofobux.makefile

**Plugin List**:
- AuraSkills 2.2.3
- AuraMobs 2.1.0

**Additional Information**: This issue might be linked to how XP or damage is calculated or displayed through the BossBar. Logs show the exception as related to the BossBarManager.

### Agreements

- [X] I am running the latest version of AuraSkills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/auraskills/incompatibilities)
- [X] My version of Minecraft is supported by AuraSkills

**Comment by Archy-X** [comment]
This should already be fixed on the latest dev build: https://aurelium.dev/auraskills/download?channel=dev

**Comment by thisisaef** [comment]
Ok, Thank u
