### ISSUE TITLE
Mobs do Excessive Durability Damage to Armor

### ISSUE THREAD

**Issue by codster6789** [Archy-X/AuraSkills#333]
### Server software and version

Pufferfish 1.21.1-18-63ce67d
Game Version: 1.21.1

### Expected behavior

Durability ticks away based on the .6s system the game runs on, this wouldn't normally be affected based on what is shown below.

### Actual behavior

Armor's durability depletes at a rapid pace, depending on the # of mobs hitting you this could destroy an entire set of netherite armor in just a few seconds. 

### How to reproduce

Run any new version of AuraSkills (tested down to 2.2.1) and have any group of mobs hit you, watching the durability of your armor deplete at a rapid pace. 

### Additional information

https://github.com/user-attachments/assets/a36723f0-e0b5-4504-b311-0eea650d96cf

### Agreements

- [X] I am running the latest version of AuraSkills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/auraskills/incompatibilities)
- [X] My version of Minecraft is supported by AuraSkills

**Comment by makegodhere** [comment]
same to
this happen only with slimes and magma cubes
and this effect not only for items durability - problem in instadamage from slimes - they deal damage so fast without delay

and another strange thing
on clear install with default config file - all good

**Comment by Archy-X** [comment]
I've determined this to be a bug with the damage_reduction trait (in stats.yml) and the mob_master ability (abilities.yml). While I investigate a fix, you should be able to fix it for now if you disable both those features.

**Comment by Archy-X** [comment]
I believe I have fixed the issue in the latest dev build: https://aurelium.dev/auraskills/download?channel=dev

Please test this and let me know if you find any issues related to damage and plugin compatibility, since this fix could potentially affect other plugins.

**Comment by makegodhere** [comment]
> I believe I have fixed the issue in the latest dev build: https://aurelium.dev/auraskills/download?channel=dev
> 
> Please test this and let me know if you find any issues related to damage and plugin compatibility, since this fix could potentially affect other plugins.

fixed thx
