### ISSUE TITLE
Enchanter Skill Increases All Experience, Causing Plugin Conflicts

### ISSUE THREAD

**Issue by DimaSergeew** [Archy-X/AuraSkills#336]
### Server software and version

purpur 1.20.4

### Expected behavior

The Enchanter skill should only increase experience gained from specific sources, such as mob kills, without affecting other plugins that handle experience differently.

### Actual behavior

The Enchanter skill currently increases all experience gained universally. This affects plugins like AxGraves and BottledExp, allowing players to receive more experience than intended. For example:

AxGraves: Waiting for the timer to end results in more experience than was originally intended.
BottledExp: Players can obtain more experience from a bottle than was placed due to the experience multiplier.

### How to reproduce

Equip the Enchanter skill in the Зачарователь (Enchanter) skill tree.
Use a plugin such as AxGraves or BottledExp that manages experience.
Perform actions that grant experience through these plugins (e.g., using a grave or a bottled experience item).
Observe that the experience gained is multiplied beyond the intended amo

### Additional information

Plugins Affected: AxGraves, BottledExp, and potentially others that handle experience.
Skill Details: The Enchanter skill is intended to enhance specific sources of experience rather than applying a global multiplier.
Suggested Fix: Modify the Enchanter skill so that its experience multiplier only applies to designated sources, such as experience from mob kills, and does not interfere with other plugins' experience handling mechanisms.

### Agreements

- [X] I am running the latest version of AuraSkills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/auraskills/incompatibilities)
- [X] My version of Minecraft is supported by AuraSkills

**Comment by Archy-X** [comment]
Unfortunately the Bukkit API doesn't store the source of an experience orb entity, and there doesn't seem to be an easy to access the exp orb entity when it is created on entity death or bottle splash. Any solution that I can think of would be more complex to implement so while this is something I want to fix, it likely won't be an immediate priority.
