### ISSUE TITLE
Max health item attribute modifier bug

### ISSUE THREAD

**Issue by andris155** [Archy-X/AuraSkills#45]
**Server Version and Software**
Paper 1.17.1

**Description**
If use max health item attribute modifier on items, the extra heart icons not added to the currently player health.

**How To Reproduce**
1. Unlock extra health in AureliumSkills.
2. Use max health item attribute modifier on items.
3. The extra heart icons not added to the currently player health.

**Expected behavior**
If use max health item attribute modifier on items, the extra heart icons added to the currently player health.

**Actual behavior**
If use max health item attribute modifier on items, the extra heart icons not added to the currently player health.

**Comment by andris155** [comment]
https://www.youtube.com/watch?v=1DoqC5CADbM

**Comment by kn-km** [comment]
The same as max mana modifier.

**Comment by Archy-X** [comment]
Try using the built in Aurelium Skills armor health modifiers using:
/skills armor modifier add health [amount]

**Comment by andris155** [comment]
This may solve the error for new devices, but not on existing ones that have the vanilla attribute modifier.

**Comment by JosTheDude** [comment]
Bumping, the bug is applying to custom made items such that it sets the player's health back to 20 (or whatever health they gained from skills as well) whenever they're hit by a player.

**Comment by Ocawesome101** [comment]
this also affects the `generic.max_health` attribute when set using commands, which is _thoroughly_ annoying.

**Comment by Archy-X** [comment]
I believe this should be solved after testing with the latest plugin version on a 1.20.4 server. Reopen if you still experience this issue.
