### ISSUE TITLE
Allow over max mana not working

### ISSUE THREAD

**Issue by PrimalPower** [Archy-X/AuraSkills#88]
### Server software and version

Paper 1.18.1 #177 Aurelium skills beta 1.2.9

### Expected behavior

I set the config option for allow over max mana to false. It should set the mana to my max mana if my max mana decreasss and my mana is over max mana

### Actual behavior

It doesn’t do anything and the mana can be over max

### How to reproduce

Use commands for max alchemy.
Get 5 effects
Then remove them
Set allow over max mana to false
You should have over max mana

### Additional information

Nothing

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by Archy-X** [comment]
This has been fixed
