### ISSUE TITLE
Unable to access Sorcery ability branch in skills gui

### ISSUE THREAD

**Issue by redstonepowder** [Archy-X/AuraSkills#90]
### Server software and version

Minecraft Java 1.18.1 || git-paper-198

### Expected behavior

Clicking on the Sorcery icon will direct you to the Sorcery ability branch.

### Actual behavior

Clicking on the sorcery icon does nothing.

### How to reproduce

Access the skills gui by by typing the `/skills` command. Click on the Sorcery icon.

### Additional information

I'm unable to attach a video example of the issue, what other medium can I use to share it?

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by Archy-X** [comment]
I'm unable to reproduce your issue, do you have any other plugins that could possibly interfere with it (specifically the blaze rod item)?

**Comment by redstonepowder** [comment]
There are no plugins that make use of the blazerod, nor any other plugins that make use of a gui.
