### ISSUE TITLE
Decent Holograms Support

### ISSUE THREAD

**Issue by iCaitlyn** [Archy-X/AuraSkills#91]
### Feature description

Would it be possible for "[Decent Holograms](https://wiki.decentholograms.eu/api/get-started)" to be supported as an alternative to Holographic Displays?

**Comment by enigma072485** [comment]
I would love to see this added....or make it an option to choose which Hologram plugin we could use.....
If anything.....Please consider it! <3

**Comment by Archy-X** [comment]
This has been added for a while

**Comment by enigma072485** [comment]
Yeah, it's been a couple of years.... Thanks for the closure tho. 🥰
